// flow-typed signature: 90d48fa6f64a1c59fc9af267c7f95e9b
// flow-typed version: <<STUB>>/react-transform-log-render_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transform-log-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transform-log-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transform-log-render/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transform-log-render/lib/index.js' {
  declare module.exports: $Exports<'react-transform-log-render/lib/index'>;
}
